/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package citbyui.cit260.sudoku.frames;

/**
 *
 * @author dsteen
 */
public class EnterPlayerNames extends javax.swing.JFrame {

    /**
     * Creates new form EnterPlayerNames
     */
    public EnterPlayerNames() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpBodyNames = new javax.swing.JPanel();
        jpTitleNames = new javax.swing.JPanel();
        jlNames = new javax.swing.JLabel();
        jlPlayerName = new javax.swing.JLabel();
        jtNameInput = new javax.swing.JTextField();
        jbNames = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enter Player Names");

        jpBodyNames.setBackground(new java.awt.Color(102, 255, 102));
        jpBodyNames.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpTitleNames.setBackground(new java.awt.Color(102, 255, 102));

        jlNames.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jlNames.setForeground(new java.awt.Color(0, 51, 255));
        jlNames.setText("Enter the name of the player below:");

        javax.swing.GroupLayout jpTitleNamesLayout = new javax.swing.GroupLayout(jpTitleNames);
        jpTitleNames.setLayout(jpTitleNamesLayout);
        jpTitleNamesLayout.setHorizontalGroup(
            jpTitleNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlNames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpTitleNamesLayout.setVerticalGroup(
            jpTitleNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlNames)
        );

        jlPlayerName.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jlPlayerName.setForeground(new java.awt.Color(0, 51, 255));
        jlPlayerName.setText("Players Name");

        jtNameInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbNames.setText("Continue");
        jbNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNamesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBodyNamesLayout = new javax.swing.GroupLayout(jpBodyNames);
        jpBodyNames.setLayout(jpBodyNamesLayout);
        jpBodyNamesLayout.setHorizontalGroup(
            jpBodyNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyNamesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBodyNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpTitleNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBodyNamesLayout.createSequentialGroup()
                        .addComponent(jlPlayerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpBodyNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtNameInput)
                            .addComponent(jbNames, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBodyNamesLayout.setVerticalGroup(
            jpBodyNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyNamesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpTitleNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jpBodyNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPlayerName)
                    .addComponent(jtNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbNames, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBodyNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBodyNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNamesActionPerformed
        GameFrame gameFrame = new GameFrame();
        gameFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbNamesActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbNames;
    private javax.swing.JLabel jlNames;
    private javax.swing.JLabel jlPlayerName;
    private javax.swing.JPanel jpBodyNames;
    private javax.swing.JPanel jpTitleNames;
    private javax.swing.JTextField jtNameInput;
    // End of variables declaration//GEN-END:variables
}
