/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package citbyui.cit260.sudoku.frames;

import citbyui.cit260.sudoku.controls.Sudoku;





/**
 *
 * @author dsteen
 */
public class GameFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBodyGame = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlGame = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jpGameMenu = new javax.swing.JPanel();
        jbNewGame = new javax.swing.JButton();
        jbPreferences = new javax.swing.JButton();
        jbStatistics = new javax.swing.JButton();
        jbGameHelp = new javax.swing.JButton();
        jbGameQuit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMessageArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBodyGame.setBackground(new java.awt.Color(102, 255, 102));
        jpBodyGame.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jlGame.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jlGame.setForeground(new java.awt.Color(0, 51, 255));
        jlGame.setText("Sudoku Game");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jlGame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlGame))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        jpGameMenu.setBackground(new java.awt.Color(0, 51, 255));
        jpGameMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbNewGame.setText("New Game");
        jbNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewGameActionPerformed(evt);
            }
        });

        jbPreferences.setText("Preferences");
        jbPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreferencesActionPerformed(evt);
            }
        });

        jbStatistics.setText("Statistics");
        jbStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStatisticsActionPerformed(evt);
            }
        });

        jbGameHelp.setText("Help");
        jbGameHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGameHelpActionPerformed(evt);
            }
        });

        jbGameQuit.setText("Quit");
        jbGameQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGameQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpGameMenuLayout = new javax.swing.GroupLayout(jpGameMenu);
        jpGameMenu.setLayout(jpGameMenuLayout);
        jpGameMenuLayout.setHorizontalGroup(
            jpGameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGameMenuLayout.createSequentialGroup()
                .addGroup(jpGameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGameMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpGameMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbPreferences))
                    .addGroup(jpGameMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpGameMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbGameHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpGameMenuLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jbGameQuit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpGameMenuLayout.setVerticalGroup(
            jpGameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGameMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNewGame)
                .addGap(18, 18, 18)
                .addComponent(jbPreferences)
                .addGap(18, 18, 18)
                .addComponent(jbStatistics)
                .addGap(18, 18, 18)
                .addComponent(jbGameHelp)
                .addGap(28, 28, 28)
                .addComponent(jbGameQuit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtMessageArea.setColumns(20);
        jtMessageArea.setRows(5);
        jScrollPane1.setViewportView(jtMessageArea);

        javax.swing.GroupLayout jpBodyGameLayout = new javax.swing.GroupLayout(jpBodyGame);
        jpBodyGame.setLayout(jpBodyGameLayout);
        jpBodyGameLayout.setHorizontalGroup(
            jpBodyGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpBodyGameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBodyGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jpBodyGameLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jpGameMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpBodyGameLayout.setVerticalGroup(
            jpBodyGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyGameLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpBodyGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBodyGameLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jpGameMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpBodyGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpBodyGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGameQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGameQuitActionPerformed
        Sudoku.mainFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbGameQuitActionPerformed

    private void jbGameHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGameHelpActionPerformed
        HelpFrame helpFrame = new HelpFrame();
        helpFrame.setVisible(true);
    }//GEN-LAST:event_jbGameHelpActionPerformed

    private void jbStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStatisticsActionPerformed
        //this.displayStatistics();
    }//GEN-LAST:event_jbStatisticsActionPerformed

    private void jbPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreferencesActionPerformed
        PreferencesFrame gamePreferences = new PreferencesFrame();
        
        gamePreferences.setVisible(true);
    }//GEN-LAST:event_jbPreferencesActionPerformed

    private void jbNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbNewGameActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbGameHelp;
    private javax.swing.JButton jbGameQuit;
    private javax.swing.JButton jbNewGame;
    private javax.swing.JButton jbPreferences;
    private javax.swing.JButton jbStatistics;
    private javax.swing.JLabel jlGame;
    private javax.swing.JPanel jpBodyGame;
    private javax.swing.JPanel jpGameMenu;
    private javax.swing.JTextArea jtMessageArea;
    // End of variables declaration//GEN-END:variables
}
