/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package citbyui.cit260.sudoku.frames;

/**
 *
 * @author Ethan Nelson
 */
public class GamePreferences extends javax.swing.JFrame {

    /**
     * Creates new form GamePreferences
     */
    public GamePreferences() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpBodyNames = new javax.swing.JPanel();
        jpTitleNames = new javax.swing.JPanel();
        jlNames = new javax.swing.JLabel();
        jtNameInput = new javax.swing.JTextField();
        jbNames1 = new javax.swing.JButton();
        jtTitleHelp = new javax.swing.JLabel();
        jtTitleHelp1 = new javax.swing.JLabel();
        javax.swing.JButton jbQuitHelp = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setFocusCycleRoot(false);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jpBodyNames.setBackground(new java.awt.Color(102, 255, 102));
        jpBodyNames.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpTitleNames.setBackground(new java.awt.Color(102, 255, 102));

        jlNames.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jlNames.setForeground(new java.awt.Color(0, 51, 255));
        jlNames.setText("Enter the number of boxes you want the board to fill");

        javax.swing.GroupLayout jpTitleNamesLayout = new javax.swing.GroupLayout(jpTitleNames);
        jpTitleNames.setLayout(jpTitleNamesLayout);
        jpTitleNamesLayout.setHorizontalGroup(
            jpTitleNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTitleNamesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpTitleNamesLayout.setVerticalGroup(
            jpTitleNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlNames, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jtNameInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbNames1.setText("Apply");
        jbNames1.setActionCommand("Main Menu");
        jbNames1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNames1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBodyNamesLayout = new javax.swing.GroupLayout(jpBodyNames);
        jpBodyNames.setLayout(jpBodyNamesLayout);
        jpBodyNamesLayout.setHorizontalGroup(
            jpBodyNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyNamesLayout.createSequentialGroup()
                .addGroup(jpBodyNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBodyNamesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpTitleNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBodyNamesLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jtNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBodyNamesLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jbNames1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBodyNamesLayout.setVerticalGroup(
            jpBodyNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyNamesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpTitleNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jtNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNames1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jtTitleHelp.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jtTitleHelp.setForeground(new java.awt.Color(0, 51, 255));
        jtTitleHelp.setText("Sudoku Preferences");

        jtTitleHelp1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jtTitleHelp1.setForeground(new java.awt.Color(0, 51, 255));
        jtTitleHelp1.setText("Game Difficulty");

        jbQuitHelp.setText("Return");
        jbQuitHelp.setActionCommand("Main Menu");
        jbQuitHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jtTitleHelp1)
                        .addGap(426, 426, 426))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpBodyNames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jtTitleHelp)
                        .addGap(216, 216, 216))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbQuitHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtTitleHelp)
                .addGap(9, 9, 9)
                .addComponent(jtTitleHelp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpBodyNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jbQuitHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbQuitHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitHelpActionPerformed
        GameFrame gameFrame = new GameFrame();
        gameFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbQuitHelpActionPerformed

    private void jbNames1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNames1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbNames1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePreferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePreferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePreferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePreferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePreferences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbNames1;
    private javax.swing.JLabel jlNames;
    private javax.swing.JPanel jpBodyNames;
    private javax.swing.JPanel jpTitleNames;
    private javax.swing.JTextField jtNameInput;
    private javax.swing.JLabel jtTitleHelp;
    private javax.swing.JLabel jtTitleHelp1;
    // End of variables declaration//GEN-END:variables
}
