/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package citbyui.cit260.sudoku.frames;

import citbyui.cit260.sudoku.controls.HelpMenuControl;
import citbyui.cit260.sudoku.enums.HelpStatus;
import citbyui.cit260.sudoku.exceptions.SudokuException;

/**
 *
 * @author dsteen
 */
public class HelpFrame extends javax.swing.JFrame {
    HelpMenuControl helpCommands = new HelpMenuControl();

    /**
     * Creates new form HelpFrame
     */
    public HelpFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public HelpMenuControl getHelpCommands() {
        return helpCommands;
    }
    
    private void displayHelpText(HelpStatus command) {
        try {
            String helpText = this.helpCommands.getHelpText(command);
            this.jtHelpText.setText(helpText);
        } catch (SudokuException ex) {
            this.jtHelpText.setText(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBodyHelp = new javax.swing.JPanel();
        jpTitleHelp = new javax.swing.JPanel();
        jtTitleHelp = new javax.swing.JLabel();
        jpMenuHelp = new javax.swing.JPanel();
        jbBoardHelp = new javax.swing.JButton();
        jbGameHelp = new javax.swing.JButton();
        jbLocationHelp = new javax.swing.JButton();
        jbMarkerHelp = new javax.swing.JButton();
        jbQuitHelp = new javax.swing.JButton();
        jtTextHelp = new javax.swing.JScrollPane();
        jtHelpText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBodyHelp.setBackground(new java.awt.Color(102, 255, 102));
        jpBodyHelp.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpTitleHelp.setBackground(new java.awt.Color(102, 255, 102));

        jtTitleHelp.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jtTitleHelp.setForeground(new java.awt.Color(0, 51, 255));
        jtTitleHelp.setText("Sudoku Help");

        javax.swing.GroupLayout jpTitleHelpLayout = new javax.swing.GroupLayout(jpTitleHelp);
        jpTitleHelp.setLayout(jpTitleHelpLayout);
        jpTitleHelpLayout.setHorizontalGroup(
            jpTitleHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleHelpLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jtTitleHelp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpTitleHelpLayout.setVerticalGroup(
            jpTitleHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTitleHelpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtTitleHelp))
        );

        jpMenuHelp.setBackground(new java.awt.Color(0, 51, 255));

        jbBoardHelp.setText("Board");
        jbBoardHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBoardHelpActionPerformed(evt);
            }
        });

        jbGameHelp.setText("Game");
        jbGameHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGameHelpActionPerformed(evt);
            }
        });

        jbLocationHelp.setText("Location");
        jbLocationHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLocationHelpActionPerformed(evt);
            }
        });

        jbMarkerHelp.setText("Marker");
        jbMarkerHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMarkerHelpActionPerformed(evt);
            }
        });

        jbQuitHelp.setText("Return");
        jbQuitHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuHelpLayout = new javax.swing.GroupLayout(jpMenuHelp);
        jpMenuHelp.setLayout(jpMenuHelpLayout);
        jpMenuHelpLayout.setHorizontalGroup(
            jpMenuHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbLocationHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbGameHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbBoardHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbMarkerHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jpMenuHelpLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jbQuitHelp)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jpMenuHelpLayout.setVerticalGroup(
            jpMenuHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbBoardHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGameHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbLocationHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbMarkerHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jbQuitHelp)
                .addContainerGap())
        );

        jtTextHelp.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtHelpText.setEditable(false);
        jtHelpText.setColumns(20);
        jtHelpText.setLineWrap(true);
        jtHelpText.setRows(5);
        jtHelpText.setWrapStyleWord(true);
        jtHelpText.setFocusable(false);
        jtHelpText.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jtHelpText.setMinimumSize(new java.awt.Dimension(110, 28));
        jtTextHelp.setViewportView(jtHelpText);

        javax.swing.GroupLayout jpBodyHelpLayout = new javax.swing.GroupLayout(jpBodyHelp);
        jpBodyHelp.setLayout(jpBodyHelpLayout);
        jpBodyHelpLayout.setHorizontalGroup(
            jpBodyHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTitleHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpBodyHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMenuHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtTextHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBodyHelpLayout.setVerticalGroup(
            jpBodyHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyHelpLayout.createSequentialGroup()
                .addComponent(jpTitleHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpBodyHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpMenuHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTextHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBodyHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBodyHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbQuitHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitHelpActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbQuitHelpActionPerformed

    private void jbBoardHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBoardHelpActionPerformed
        displayHelpText(HelpStatus.BOARD);
    }//GEN-LAST:event_jbBoardHelpActionPerformed

    private void jbGameHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGameHelpActionPerformed
        displayHelpText(HelpStatus.GAME);
    }//GEN-LAST:event_jbGameHelpActionPerformed

    private void jbLocationHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLocationHelpActionPerformed
        displayHelpText(HelpStatus.LOCATION);
    }//GEN-LAST:event_jbLocationHelpActionPerformed

    private void jbMarkerHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMarkerHelpActionPerformed
        displayHelpText(HelpStatus.MARKER);
    }//GEN-LAST:event_jbMarkerHelpActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbBoardHelp;
    private javax.swing.JButton jbGameHelp;
    private javax.swing.JButton jbLocationHelp;
    private javax.swing.JButton jbMarkerHelp;
    private javax.swing.JButton jbQuitHelp;
    private javax.swing.JPanel jpBodyHelp;
    private javax.swing.JPanel jpMenuHelp;
    private javax.swing.JPanel jpTitleHelp;
    private javax.swing.JTextArea jtHelpText;
    private javax.swing.JScrollPane jtTextHelp;
    private javax.swing.JLabel jtTitleHelp;
    // End of variables declaration//GEN-END:variables
}
